name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Build the Docker image
        run: docker build . --no-cache --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Build Docker Compose
        run: docker compose build --no-cache
